# 
TARGET = libGEL.so

BIN_DIR=build
LIBSRCS = $(wildcard */*.cpp) $(wildcard */*.c)
LIBOBJS = $(LIBSRCS:.cpp=.o) 

	
CXX = g++
CXXFLAGS = -Wall -O3 -std=c++11
LDFLAGS += -I./

$(TARGET): $(LIBOBJS)
	$(CXX) $(CXXFLAGS) -o $@ $(LIBOBJS)  $(LDFLAGS)

.PHONY: clean test
clean: 
	rm $(LIBOBJS)
	
depend: $(LIBSRCS)
	makedepend -Y $(LIBSRCS) 2> /dev/null
# DO NOT DELETE
